NOISSUE - Add README
mainflux/license pull request #19
Opened 2020-03-17 17:44 UTC by dusanb94

2020-03-17 17:50 UTC, drasko submitted a review, later dismissed
LGTM

2020-03-17 20:37 UTC, manuio requested changes

2020-03-17 20:37 UTC, manuio commented on README.md
> +| MF_LICENSE_DB_SSL_ROOT_CERT | DB SSL   root cert        |                |
fix `SSL   root`

2020-03-17 20:38 UTC, manuio requested changes

2020-03-17 20:38 UTC, manuio commented on README.md
> +| MF_AUTH_URL                 | Auth service UR;          | localhost:8181 |
Fix `UR;`

2020-03-24 07:55 UTC, manuio approved these changes
LGTM

2020-03-24 10:41 UTC, nmarcetic approved these changes

2020-03-24 11:06 UTC, drasko approved these changes
LGTM

2020-03-24 11:07 UTC, merged