Fix validation request
mainflux/license pull request #23
Opened 2020-03-30 19:24 UTC by dusanb94

Use encrypted endpoint for validation.

2020-03-30 19:36 UTC, manuio requested changes

2020-03-30 19:36 UTC, manuio commented on pkg/validator/validator.go
> +	Client string `json:""`
is this normal? ``json:""``

2020-03-31 09:12 UTC, nmarcetic approved these changes

2020-03-31 11:23 UTC, drasko approved these changes
LGTM

2020-03-31 11:26 UTC, manuio approved these changes
LGTM

2020-03-31 11:26 UTC, merged